// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Dialogue dialogue
//
// swagger:model Dialogue
type Dialogue struct {

	// character name
	CharacterName string `json:"CharacterName,omitempty"`

	// quote
	Quote string `json:"Quote,omitempty"`
}

// Validate validates this dialogue
func (m *Dialogue) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Dialogue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Dialogue) UnmarshalBinary(b []byte) error {
	var res Dialogue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
