// Code generated by go-swagger; DO NOT EDIT.

package dialogue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new dialogue API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for dialogue API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetDialogueRandom(params *GetDialogueRandomParams) (*GetDialogueRandomOK, error)

	GetDialogueRandomByCharacter(params *GetDialogueRandomByCharacterParams) (*GetDialogueRandomByCharacterOK, error)

	GetDialoguesByCharacter(params *GetDialoguesByCharacterParams) (*GetDialoguesByCharacterOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetDialogueRandom returns a random dialogue of the movie
*/
func (a *Client) GetDialogueRandom(params *GetDialogueRandomParams) (*GetDialogueRandomOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetDialogueRandomParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getDialogueRandom",
		Method:             "GET",
		PathPattern:        "/dialogue/random",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetDialogueRandomReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetDialogueRandomOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getDialogueRandom: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetDialogueRandomByCharacter returns a random dialogue of the given character of the movie
*/
func (a *Client) GetDialogueRandomByCharacter(params *GetDialogueRandomByCharacterParams) (*GetDialogueRandomByCharacterOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetDialogueRandomByCharacterParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getDialogueRandomByCharacter",
		Method:             "GET",
		PathPattern:        "/dialogue/random/byCharacter",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetDialogueRandomByCharacterReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetDialogueRandomByCharacterOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getDialogueRandomByCharacter: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetDialoguesByCharacter retuns all available dialogues of the given character of the movie
*/
func (a *Client) GetDialoguesByCharacter(params *GetDialoguesByCharacterParams) (*GetDialoguesByCharacterOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetDialoguesByCharacterParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getDialoguesByCharacter",
		Method:             "GET",
		PathPattern:        "/dialogues/character",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetDialoguesByCharacterReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetDialoguesByCharacterOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getDialoguesByCharacter: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
