// Code generated by go-swagger; DO NOT EDIT.

package dialogue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"andaz-api/pkg/models"
)

// GetDialogueRandomReader is a Reader for the GetDialogueRandom structure.
type GetDialogueRandomReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDialogueRandomReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDialogueRandomOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDialogueRandomOK creates a GetDialogueRandomOK with default headers values
func NewGetDialogueRandomOK() *GetDialogueRandomOK {
	return &GetDialogueRandomOK{}
}

/*GetDialogueRandomOK handles this case with default header values.

Successful operation.
*/
type GetDialogueRandomOK struct {
	Payload *models.Dialogue
}

func (o *GetDialogueRandomOK) Error() string {
	return fmt.Sprintf("[GET /dialogue/random][%d] getDialogueRandomOK  %+v", 200, o.Payload)
}

func (o *GetDialogueRandomOK) GetPayload() *models.Dialogue {
	return o.Payload
}

func (o *GetDialogueRandomOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Dialogue)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
