// Code generated by go-swagger; DO NOT EDIT.

package dialogue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDialogueRandomByCharacterParams creates a new GetDialogueRandomByCharacterParams object
// with the default values initialized.
func NewGetDialogueRandomByCharacterParams() *GetDialogueRandomByCharacterParams {
	var ()
	return &GetDialogueRandomByCharacterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDialogueRandomByCharacterParamsWithTimeout creates a new GetDialogueRandomByCharacterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDialogueRandomByCharacterParamsWithTimeout(timeout time.Duration) *GetDialogueRandomByCharacterParams {
	var ()
	return &GetDialogueRandomByCharacterParams{

		timeout: timeout,
	}
}

// NewGetDialogueRandomByCharacterParamsWithContext creates a new GetDialogueRandomByCharacterParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDialogueRandomByCharacterParamsWithContext(ctx context.Context) *GetDialogueRandomByCharacterParams {
	var ()
	return &GetDialogueRandomByCharacterParams{

		Context: ctx,
	}
}

// NewGetDialogueRandomByCharacterParamsWithHTTPClient creates a new GetDialogueRandomByCharacterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDialogueRandomByCharacterParamsWithHTTPClient(client *http.Client) *GetDialogueRandomByCharacterParams {
	var ()
	return &GetDialogueRandomByCharacterParams{
		HTTPClient: client,
	}
}

/*GetDialogueRandomByCharacterParams contains all the parameters to send to the API endpoint
for the get dialogue random by character operation typically these are written to a http.Request
*/
type GetDialogueRandomByCharacterParams struct {

	/*CharacterName
	  Name of chanracter whose dialogue is returned.

	*/
	CharacterName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get dialogue random by character params
func (o *GetDialogueRandomByCharacterParams) WithTimeout(timeout time.Duration) *GetDialogueRandomByCharacterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get dialogue random by character params
func (o *GetDialogueRandomByCharacterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get dialogue random by character params
func (o *GetDialogueRandomByCharacterParams) WithContext(ctx context.Context) *GetDialogueRandomByCharacterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get dialogue random by character params
func (o *GetDialogueRandomByCharacterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get dialogue random by character params
func (o *GetDialogueRandomByCharacterParams) WithHTTPClient(client *http.Client) *GetDialogueRandomByCharacterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get dialogue random by character params
func (o *GetDialogueRandomByCharacterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCharacterName adds the characterName to the get dialogue random by character params
func (o *GetDialogueRandomByCharacterParams) WithCharacterName(characterName string) *GetDialogueRandomByCharacterParams {
	o.SetCharacterName(characterName)
	return o
}

// SetCharacterName adds the characterName to the get dialogue random by character params
func (o *GetDialogueRandomByCharacterParams) SetCharacterName(characterName string) {
	o.CharacterName = characterName
}

// WriteToRequest writes these params to a swagger request
func (o *GetDialogueRandomByCharacterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param characterName
	if err := r.SetPathParam("characterName", o.CharacterName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
