// Code generated by go-swagger; DO NOT EDIT.

package dialogue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDialoguesByCharacterParams creates a new GetDialoguesByCharacterParams object
// with the default values initialized.
func NewGetDialoguesByCharacterParams() *GetDialoguesByCharacterParams {
	var ()
	return &GetDialoguesByCharacterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDialoguesByCharacterParamsWithTimeout creates a new GetDialoguesByCharacterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDialoguesByCharacterParamsWithTimeout(timeout time.Duration) *GetDialoguesByCharacterParams {
	var ()
	return &GetDialoguesByCharacterParams{

		timeout: timeout,
	}
}

// NewGetDialoguesByCharacterParamsWithContext creates a new GetDialoguesByCharacterParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDialoguesByCharacterParamsWithContext(ctx context.Context) *GetDialoguesByCharacterParams {
	var ()
	return &GetDialoguesByCharacterParams{

		Context: ctx,
	}
}

// NewGetDialoguesByCharacterParamsWithHTTPClient creates a new GetDialoguesByCharacterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDialoguesByCharacterParamsWithHTTPClient(client *http.Client) *GetDialoguesByCharacterParams {
	var ()
	return &GetDialoguesByCharacterParams{
		HTTPClient: client,
	}
}

/*GetDialoguesByCharacterParams contains all the parameters to send to the API endpoint
for the get dialogues by character operation typically these are written to a http.Request
*/
type GetDialoguesByCharacterParams struct {

	/*CharacterName
	  Name of chanracter whose dialogues are returned.

	*/
	CharacterName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get dialogues by character params
func (o *GetDialoguesByCharacterParams) WithTimeout(timeout time.Duration) *GetDialoguesByCharacterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get dialogues by character params
func (o *GetDialoguesByCharacterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get dialogues by character params
func (o *GetDialoguesByCharacterParams) WithContext(ctx context.Context) *GetDialoguesByCharacterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get dialogues by character params
func (o *GetDialoguesByCharacterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get dialogues by character params
func (o *GetDialoguesByCharacterParams) WithHTTPClient(client *http.Client) *GetDialoguesByCharacterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get dialogues by character params
func (o *GetDialoguesByCharacterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCharacterName adds the characterName to the get dialogues by character params
func (o *GetDialoguesByCharacterParams) WithCharacterName(characterName string) *GetDialoguesByCharacterParams {
	o.SetCharacterName(characterName)
	return o
}

// SetCharacterName adds the characterName to the get dialogues by character params
func (o *GetDialoguesByCharacterParams) SetCharacterName(characterName string) {
	o.CharacterName = characterName
}

// WriteToRequest writes these params to a swagger request
func (o *GetDialoguesByCharacterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param characterName
	if err := r.SetPathParam("characterName", o.CharacterName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
